[package]
name = "asterix"
version = "0.2.4"
authors = ["wcampbell"]
edition = "2018"
categories = ["encoding", "parsing"]
keywords = ["asterix", "radar", "aviation", "network", "protocol"]
license = "MIT"
readme = "README.md"
description = "Encode/Decode for ASTERIX protocol using the deku library"
repository = "https://github.com/wcampbell0x2a/asterix-rs"

[workspace]
members = [
    "asterix-derive",
]

[dependencies]
deku = "0.8.0"
asterix-derive = { version = "^0.2.0", path = "asterix-derive" }
